name: build

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: "recursive"

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.2

      - name: Build and test
        run: make

      - name: Dry run deploy
        run: make version POETRY_EXTRA_ARGS='--dry-run'
        env:
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASS: ${{ secrets.PYPI_PASS }}
